name: Continuous Integration

on:
  pull_request:
    branches:
      - main
      - develop
      - sprint-*

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Format code with Prettier
        run: npm run format:check

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run Stylelint
        run: npm run stylelint || echo "Stylelint check skipped"

      - name: Type check
        run: npm run typecheck

  test:
    runs-on: ubuntu-latest
    # temporarily disabled
    continue-on-error: true

    env:
      NEXT_PUBLIC_CTP_PROJECT_KEY: ${{ secrets.NEXT_PUBLIC_CTP_PROJECT_KEY }}
      NEXT_PUBLIC_CTP_CLIENT_SECRET: ${{ secrets.NEXT_PUBLIC_CTP_CLIENT_SECRET }}
      NEXT_PUBLIC_CTP_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_CTP_CLIENT_ID }}
      NEXT_PUBLIC_CTP_REGION: ${{ secrets.NEXT_PUBLIC_CTP_REGION }}
      NEXT_PUBLIC_CTP_AUTH_URL: ${{ secrets.NEXT_PUBLIC_CTP_AUTH_URL }}
      NEXT_PUBLIC_CTP_API_URL: ${{ secrets.NEXT_PUBLIC_CTP_API_URL }}
      NEXT_PUBLIC_CTP_SCOPES: ${{ secrets.NEXT_PUBLIC_CTP_SCOPES }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check if tests exist
        id: check_tests
        run: |
          if find src -name "*.test.*" -o -name "*.spec.*" | grep -q .; then
            echo "has_tests=true" >> $GITHUB_OUTPUT
          else
            echo "has_tests=false" >> $GITHUB_OUTPUT
          fi

      - name: Run tests if they exist
        if: steps.check_tests.outputs.has_tests == 'true'
        run: npm test

      - name: Skip tests
        if: steps.check_tests.outputs.has_tests == 'false'
        run: echo "No tests found. Skipping test step."

  build:
    runs-on: ubuntu-latest
    needs: [format, lint]

    env:
      NEXT_PUBLIC_CTP_PROJECT_KEY: ${{ secrets.NEXT_PUBLIC_CTP_PROJECT_KEY }}
      NEXT_PUBLIC_CTP_CLIENT_SECRET: ${{ secrets.NEXT_PUBLIC_CTP_CLIENT_SECRET }}
      NEXT_PUBLIC_CTP_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_CTP_CLIENT_ID }}
      NEXT_PUBLIC_CTP_REGION: ${{ secrets.NEXT_PUBLIC_CTP_REGION }}
      NEXT_PUBLIC_CTP_AUTH_URL: ${{ secrets.NEXT_PUBLIC_CTP_AUTH_URL }}
      NEXT_PUBLIC_CTP_API_URL: ${{ secrets.NEXT_PUBLIC_CTP_API_URL }}
      NEXT_PUBLIC_CTP_SCOPES: ${{ secrets.NEXT_PUBLIC_CTP_SCOPES }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build
