name: Renovate
on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:
jobs:
  renovate:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v41.0.16
        with:
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
