name: Request Review on PR Open

on:
  pull_request:
    types: [opened]

jobs:
  automate-review:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Get PR Author
        id: pr_author
        run: echo "author=${{ github.event.pull_request.user.login }}" >> $GITHUB_OUTPUT

      - name: Request Review for harmon1c
        if: steps.pr_author.outputs.author == 'harmon1c'
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers
          mediaType: '{"previews":["luke-cage"]}'
          token: ${{ secrets.GITHUB_TOKEN }}
          reviewers: '["dyeresko", "JuliaVasilko"]'

      - name: Request Review for dyeresko
        if: steps.pr_author.outputs.author == 'dyeresko'
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers
          mediaType: '{"previews":["luke-cage"]}'
          token: ${{ secrets.GITHUB_TOKEN }}
          reviewers: '["harmon1c", "JuliaVasilko"]'

      - name: Request Review for JuliaVasilko
        if: steps.pr_author.outputs.author == 'JuliaVasilko'
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers
          mediaType: '{"previews":["luke-cage"]}'
          token: ${{ secrets.GITHUB_TOKEN }}
          reviewers: '["harmon1c", "dyeresko"]'
